# -*- coding: utf-8 -*-
"""ServProAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Ks2mIE-YKse32o96Rp7-EQ048R7NW8Y

# Task
Develop an AI-driven chatbot for service recommendations, encompassing intent recognition, entity extraction, a service recommendation engine, and a dialogue flow to generate professional and optimistic responses.

## Environment Setup and Library Installation

### Subtask:
Install necessary Python libraries for NLP (e.g., NLTK, spaCy, Transformers) and potentially a framework for chatbot development or machine learning (e.g., scikit-learn, TensorFlow/PyTorch).

**Reasoning**:
To begin, I will install the specified Python libraries for natural language processing, machine learning, and chatbot development using `pip`.
"""

import subprocess
import sys

subprocess.run([sys.executable, '-m', 'pip', 'install', 'nltk', 'spacy', 'transformers', 'scikit-learn', 'torch'], check=True)

"""**Reasoning**:
The previous step successfully installed (or verified existing installations of) the necessary libraries. Now, to complete the subtask, I need to verify their successful installation by importing them and checking their versions as per the instructions.


"""

from gettext import install

import nltk
import spacy
import transformers
import sklearn
import torch

print(f"NLTK Version: {nltk.__version__}")
print(f"spaCy Version: {spacy.__version__}")
print(f"Transformers Version: {transformers.__version__}")
print(f"Scikit-learn Version: {sklearn.__version__}")
print(f"PyTorch Version: {torch.__version__}")

"""# Task
Update the `services_df` with examples of on-demand services such as plumber service, electricity service, and climatisation service, including appropriate descriptions, categories, and features.

## Update Sample Services Data

### Subtask:
Modify the `services_df` to include examples of on-demand services such as plumber service, electricity service, and climatisation service, along with appropriate descriptions, categories, and features.

**Reasoning**:
I will create a pandas DataFrame named `services_df`, populate it with the specified on-demand service examples including 'Service Name', 'Description', 'Category', and 'Features', and then display the DataFrame to confirm the data has been added correctly.
"""

import pandas as pd

# Create the services_df DataFrame with the specified columns
services_df = pd.DataFrame(columns=['Service Name', 'Description', 'Category', 'Features'])

# Add rows for on-demand services
services_df = pd.concat([
    services_df,
    pd.DataFrame([
        {
            'Service Name': 'Plumber Service',
            'Description': 'Emergency plumbing repairs, leak detection, drain cleaning, and water heater installation.',
            'Category': 'Home Repair',
            'Features': ['24/7 availability', 'Certified technicians', 'Upfront pricing', 'Guaranteed work']
        },
        {
            'Service Name': 'Electricity Service',
            'Description': 'Electrical wiring, outlet installation, circuit breaker repair, and emergency power restoration.',
            'Category': 'Utilities',
            'Features': ['Licensed electricians', 'Safety inspections', 'Quick response', 'Transparent costs']
        },
        {
            'Service Name': 'Climatisation Service',
            'Description': 'AC repair, HVAC installation, routine maintenance, and air quality solutions.',
            'Category': 'Home Comfort',
            'Features': ['Experienced HVAC pros', 'Energy efficiency audits', 'Seasonal tune-ups', 'Warranty on parts']
        }
    ])
], ignore_index=True)

# Display the services_df
print("Updated services_df:")
print(services_df)

"""## Data Collection and Preprocessing

### Subtask:
Gather and prepare data related to services, client profiles, and historical interactions. This includes cleaning, tokenization, and vectorization of text data for NLP models.

**Reasoning**:
The next logical step is to create the `clients_df` and `interactions_df` DataFrames with sample data, as specified in the instructions.
"""

import pandas as pd

# Create clients_df
clients_df = pd.DataFrame([
    {
        'Client ID': 'C001',
        'Preferences': 'Prefers eco-friendly services, interested in smart home solutions.',
        'Past Services': 'Installed smart thermostat, energy-efficient lighting upgrade.'
    },
    {
        'Client ID': 'C002',
        'Preferences': 'Values quick response times and budget-friendly options, has young children.',
        'Past Services': 'Emergency plumbing repair, regular AC maintenance.'
    },
    {
        'Client ID': 'C003',
        'Preferences': 'Needs reliable and premium services, often travels.',
        'Past Services': 'Comprehensive home security system installation, annual HVAC check-up.'
    }
])

# Create interactions_df
interactions_df = pd.DataFrame([
    {
        'Interaction ID': 'I001',
        'Client ID': 'C001',
        'Query Text': 'My smart thermostat is not connecting to the internet. Can you help?',
        'Recommended Service': 'Electricity Service'
    },
    {
        'Interaction ID': 'I002',
        'Client ID': 'C002',
        'Query Text': 'There is a strange smell coming from my AC unit. I need a technician urgently.',
        'Recommended Service': 'Climatisation Service'
    },
    {
        'Interaction ID': 'I003',
        'Client ID': 'C001',
        'Query Text': 'I want to upgrade my lighting to be more energy efficient.',
        'Recommended Service': 'Electricity Service'
    },
    {
        'Interaction ID': 'I004',
        'Client ID': 'C003',
        'Query Text': 'My water heater is leaking, I need a plumber now!',
        'Recommended Service': 'Plumber Service'
    },
    {
        'Interaction ID': 'I005',
        'Client ID': 'C002',
        'Query Text': 'My drains are slow, do you offer drain cleaning?',
        'Recommended Service': 'Plumber Service'
    }
])

print("clients_df:")
print(clients_df)
print("\ninteractions_df:")
print(interactions_df)

"""**Reasoning**:
The next step is to combine all relevant textual data, preprocess it by converting to lowercase, removing punctuation and digits, tokenizing, removing stopwords, and lemmatizing, and then vectorize the text using TfidfVectorizer, as specified in the instructions.


"""

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
import re

# Download necessary NLTK data (if not already downloaded)
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt', quiet=True)
try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet', quiet=True)
try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords', quiet=True)
# Added download for 'punkt_tab' as indicated by the error
try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab', quiet=True)

# Combine all relevant textual data into a single list
combined_text_data = []

# From services_df
combined_text_data.extend(services_df['Description'].tolist())
# Features column is a list of strings, so flatten it
for features_list in services_df['Features']:
    combined_text_data.extend(features_list)

# From clients_df
combined_text_data.extend(clients_df['Preferences'].tolist())
combined_text_data.extend(clients_df['Past Services'].tolist())

# From interactions_df
combined_text_data.extend(interactions_df['Query Text'].tolist())

# Initialize lemmatizer and stopwords
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

# Preprocessing function
def preprocess_text(text):
    text = text.lower() # Convert to lowercase
    text = re.sub(r'[^a-zA-Z\s]', '', text) # Remove punctuation and numbers
    tokens = nltk.word_tokenize(text) # Tokenize
    tokens = [word for word in tokens if word not in stop_words] # Remove stopwords
    tokens = [lemmatizer.lemmatize(word) for word in tokens] # Lemmatize
    return ' '.join(tokens) # Join tokens back into a string

# Apply preprocessing to combined text data
preprocessed_text_data = [preprocess_text(text) for text in combined_text_data]

# Vectorize the preprocessed textual data using TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=1000) # Limit features to avoid sparsity issues
text_features = tfidf_vectorizer.fit_transform(preprocessed_text_data)

print("Combined text data count:", len(combined_text_data))
print("Preprocessed text data sample:", preprocessed_text_data[0])
print("Shape of text_features (TF-IDF vectors):", text_features.shape) # Corrected print statement
print("Feature names (top 10):", tfidf_vectorizer.get_feature_names_out()[:10]) # Corrected print statement

"""## Intent Recognition and Entity Extraction (NLU)

### Subtask:
Develop or fine-tune models to accurately identify user intent and extract key entities from client queries.

**Reasoning**:
I will prepare the data for intent recognition by transforming the 'Query Text' into TF-IDF features using the `tfidf_vectorizer` that was already fitted in the previous step and then encode the 'Recommended Service' column into numerical labels.
"""

from sklearn.preprocessing import LabelEncoder

# 1a. Use the tfidf_vectorizer to transform Query Text
# First, preprocess the 'Query Text' column from interactions_df
preprocessed_queries = [preprocess_text(query) for query in interactions_df['Query Text']]
query_text_features = tfidf_vectorizer.transform(preprocessed_queries)

# 1b. Create numerical representation for 'Recommended Service' column
label_encoder = LabelEncoder()
intent_labels = label_encoder.fit_transform(interactions_df['Recommended Service'])

print("Shape of query_text_features:", query_text_features.shape)
print("Encoded intent labels (first 5):", intent_labels[:5])
print("Original service names for encoded labels:", label_encoder.inverse_transform(intent_labels[:5]))

"""**Reasoning**:
I will split the prepared `query_text_features` and `intent_labels` into training and testing sets and then train a `LogisticRegression` model on the training data to recognize user intent, finally evaluating its performance.


"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 2a. Split `query_text_features` and `intent_labels` into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    query_text_features, intent_labels, test_size=0.3, random_state=42 # Removed stratify due to small class counts
)

# 2b. Initialize and train a classification model
intent_model = LogisticRegression(random_state=42, solver='liblinear') # Using 'liblinear' solver for small datasets
intent_model.fit(X_train, y_train)

# 2c. Evaluate the trained model on the test set
y_pred = intent_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"Intent Recognition Model Accuracy: {accuracy:.2f}")
print(f"X_train shape: {X_train.shape}, X_test shape: {X_test.shape}")

"""**Reasoning**:
Now that the intent recognition model has been trained (albeit with limited data), the next step is to prepare for entity extraction using spaCy. This involves downloading a small English spaCy model as instructed.


"""

import subprocess
import sys

# 3a. Download a small English spaCy model if it's not already installed
# Check if the model is installed before attempting to download
try:
    import spacy
    spacy.load('en_core_web_sm')
    print("spaCy model 'en_core_web_sm' is already installed.")
except OSError:
    print("Downloading spaCy model 'en_core_web_sm'...")
    subprocess.run([sys.executable, '-m', 'spacy', 'download', 'en_core_web_sm'], check=True)
    print("spaCy model 'en_core_web_sm' downloaded successfully.")

"""**Reasoning**:
With the spaCy model confirmed to be installed, I will now load the model and define the `extract_entities` function to process a query and extract relevant entities from it, as per the subtask instructions.


"""

import spacy

# 3b. Import spaCy and load the downloaded model
nlp = spacy.load('en_core_web_sm')

# 4a & 4b. Define a function to extract entities
def extract_entities(query):
    doc = nlp(query)
    entities = {}
    # Example: extract 'PRODUCT', 'SERVICE' or general 'NOUN' entities as potential service-related keywords
    # For this example, let's focus on general nouns or proper nouns that might indicate a service type or an issue.
    service_keywords = []
    for token in doc:
        if token.pos_ in ('NOUN', 'PROPN') and not token.is_stop and not token.is_punct:
            service_keywords.append(token.text.lower())

    # More sophisticated entity extraction would involve custom NER or rule-based matching.
    # For this task, we'll look for general entities identified by spaCy, like products/services
    extracted_ents = []
    for ent in doc.ents:
        # For demonstration, we'll just collect all identified entities
        extracted_ents.append({'text': ent.text, 'label': ent.label_})

    entities['keywords'] = list(set(service_keywords))
    entities['named_entities'] = extracted_ents
    return entities

# Test the entity extraction function with a sample query
sample_query = interactions_df['Query Text'].iloc[0]
extracted = extract_entities(sample_query)

print(f"Sample Query: {sample_query}")
print(f"Extracted Entities: {extracted}")

"""## Service Recommendation Engine Development

### Subtask:
Implement a recommendation system (e.g., content-based, collaborative filtering, or hybrid) that uses the extracted intent and entities to suggest relevant services to clients.

**Reasoning**:
I will preprocess and vectorize the 'Description' column of the `services_df` using the previously defined `preprocess_text` function and `tfidf_vectorizer` to prepare it for content-based recommendations.
"""

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# 1. Preprocess the 'Description' column of services_df
preprocessed_service_descriptions = [preprocess_text(desc) for desc in services_df['Description']]

# 2. Vectorize the preprocessed service descriptions
service_description_features = tfidf_vectorizer.transform(preprocessed_service_descriptions)

print("Shape of service_description_features:", service_description_features.shape)
print("Sample preprocessed service description:", preprocessed_service_descriptions[0])

"""**Reasoning**:
I will define the `recommend_service` function which incorporates preprocessing, vectorization, cosine similarity for content-based recommendations, and intent prediction using the trained model and label encoder, then test it with the provided sample queries to demonstrate its functionality.


"""

def recommend_service(query_text):
    # Preprocess the query text
    preprocessed_query = preprocess_text(query_text)

    # Vectorize the preprocessed query
    query_vector = tfidf_vectorizer.transform([preprocessed_query])

    # Calculate cosine similarity with service descriptions
    similarity_scores = cosine_similarity(query_vector, service_description_features)

    # Get the index of the most similar service based on content
    content_best_match_idx = np.argmax(similarity_scores)
    content_best_service = services_df.loc[content_best_match_idx, 'Service Name']
    content_confidence = similarity_scores[0, content_best_match_idx]

    # Predict intent using the trained model
    predicted_intent_label = intent_model.predict(query_vector)
    predicted_intent_service = label_encoder.inverse_transform(predicted_intent_label)[0]

    # Combine recommendations (for this initial implementation, we'll favor content similarity
    # but note the predicted intent for further refinement)
    if content_best_service == predicted_intent_service:
        recommended_service = content_best_service
        confidence = content_confidence
    else:
        # If content and intent disagree, we could implement more complex logic.
        # For now, we'll lean on the content-based match and acknowledge the predicted intent.
        recommended_service = content_best_service
        confidence = content_confidence

    return recommended_service, confidence, predicted_intent_service

# Test the recommend_service function with sample queries
sample_query_1 = "My air conditioning unit is not working, I need it fixed."
recommended_service_1, confidence_1, predicted_intent_1 = recommend_service(sample_query_1)
print(f"Query: '{sample_query_1}'")
print(f"Recommended Service (Content): {recommended_service_1} (Confidence: {confidence_1:.2f})")
print(f"Predicted Intent: {predicted_intent_1}")

sample_query_2 = "I have a leaky faucet in my kitchen."
recommended_service_2, confidence_2, predicted_intent_2 = recommend_service(sample_query_2)
print(f"\nQuery: '{sample_query_2}'")
print(f"Recommended Service (Content): {recommended_service_2} (Confidence: {confidence_2:.2f})")
print(f"Predicted Intent: {predicted_intent_2}")

"""## Chatbot Dialogue Flow and Response Generation

### Subtask:
Design the conversational flow, including handling follow-up questions, clarifying ambiguity, and generating professional and optimistic textual responses that present service recommendations clearly.

**Reasoning**:
I will define the `generate_response` function with the specified logic for creating professional and optimistic responses, handling confidence scores and discrepancies between content-based and intent-based recommendations, and then test it with the previous sample queries.
"""

def generate_response(recommended_service, confidence, predicted_intent_service):
    response = f"Great news! I found a highly recommended service for you: **{recommended_service}**.\n"

    if confidence > 0.1: # A low threshold for demonstration with small dataset
        response += f"I'm quite confident about this recommendation (Confidence: {confidence:.2f}).\n"
    else:
        response += f"While I'm suggesting this service, I'm working with limited information (Confidence: {confidence:.2f}).\n"

    if recommended_service != predicted_intent_service:
        response += (
            f"However, I also detected a potential intent for **{predicted_intent_service}**.\n"
            "Could you please provide more details if you feel this isn't quite right, or if you had a different service in mind?\n"
        )

    response += "We're here to ensure you get the best assistance possible. How else can I help you today?"
    return response

# Test the generate_response function with the output from recommend_service
# First sample query
sample_query_1 = "My air conditioning unit is not working, I need it fixed."
recommended_service_1, confidence_1, predicted_intent_1 = recommend_service(sample_query_1)
response_1 = generate_response(recommended_service_1, confidence_1, predicted_intent_1)
print(f"--- Response for Query 1: '{sample_query_1}' ---")
print(response_1)

# Second sample query
sample_query_2 = "I have a leaky faucet in my kitchen."
recommended_service_2, confidence_2, predicted_intent_2 = recommend_service(sample_query_2)
response_2 = generate_response(recommended_service_2, confidence_2, predicted_intent_2)
print(f"\n--- Response for Query 2: '{sample_query_2}' ---")
print(response_2)

"""## Component Integration and Internal Testing

### Subtask:
Integrate all NLP and AI components (NLU, recommendation engine, dialogue manager) into a cohesive system and perform internal testing to ensure their functionality and logical flow for generating service recommendations.

## Summary:

### Data Analysis Key Findings

*   **Service Data Initialization**: The `services_df` was successfully populated with three key on-demand services: 'Plumber Service', 'Electricity Service', and 'Climatisation Service'. Each entry included a detailed description, a relevant category ('Home Repair', 'Utilities', 'Home Comfort'), and a list of specific features (e.g., '24/7 availability', 'Licensed electricians').
*   **Client and Interaction Data Setup**: `clients_df` and `interactions_df` were created to store client preferences, past service history, and historical interactions (user query and recommended service), providing a basis for context-aware recommendations.
*   **Text Data Preprocessing and Vectorization**: All textual data from `services_df`, `clients_df`, and `interactions_df` was combined, thoroughly preprocessed (lowercasing, punctuation/number removal, tokenization, stop word removal, and lemmatization), and then vectorized using `TfidfVectorizer`. The resulting TF-IDF feature matrix had a shape of (26, 90).
*   **Intent Recognition Model Performance**: A `LogisticRegression` model was trained for intent recognition. However, due to the extremely limited dataset (3 training samples), the model achieved an accuracy of 0.00% on the test set, indicating a complete lack of generalization.
*   **Entity Extraction Functionality**: A function leveraging spaCy's `en_core_web_sm` model was successfully implemented to extract general service-related keywords (nouns and proper nouns) and named entities from client queries. For a sample query like "My smart thermostat is not connecting to the internet," keywords such as "thermostat" and "internet" were extracted.
*   **Content-Based Recommendation Engine**: A recommendation system was developed using cosine similarity between vectorized user queries and service descriptions. For instance, a query about "air conditioning unit not working" correctly recommended "Climatisation Service" with a confidence of 0.23, and "leaky faucet" recommended "Plumber Service" with 0.00 confidence, although the intent model often predicted "Electricity Service" for these queries.
*   **Structured Chatbot Response Generation**: A `generate_response` function was successfully implemented to create professional and optimistic chatbot responses. It clearly states the recommended service, includes the confidence score, and explicitly addresses discrepancies between content-based recommendations and the intent model's prediction, suggesting further user input if needed.

### Insights or Next Steps

*   **Enhance Intent Recognition Model Accuracy**: The current intent recognition model's accuracy (0.00%) is severely limited by the small dataset. A critical next step is to significantly expand the training data for client queries and their corresponding service intents to build a robust and generalizable model.
*   **Develop Hybrid Recommendation Strategy**: Implement a more sophisticated recommendation strategy that intelligently combines the content-based similarity scores, the intent model's predictions, and potentially client historical data or explicit preferences to resolve conflicts and improve the relevance and confidence of service recommendations.

# Task
Install the `google-genai` library to enable communication with the Gemini API.

## Install Google GenAI Library

### Subtask:
Install the `google-genai` library to enable communication with the Gemini API.

**Reasoning**:
I will install the `google-genai` library using `pip` to fulfill the first instruction of the subtask.
"""

import subprocess
import sys

subprocess.run([sys.executable, '-m', 'pip', 'install', 'google-genai'], check=True)

"""**Reasoning**:
The `google-genai` library has been installed (or confirmed as already installed). Now, I will import the `google.generativeai` module to verify its successful installation and accessibility.


"""

import google.generativeai as genai
print("google.generativeai module imported successfully, ready to use Gemini API.")

"""**Reasoning**:
The previous step produced a FutureWarning indicating that `google.generativeai` is deprecated and `google.genai` should be used instead. I will update the import statement to use `google.genai` to address this warning.


"""

import google.genai as genai
print("google.genai module imported successfully, ready to use Gemini API.")

"""## Integrate Gemini into Response Generation

### Subtask:
Modify the existing `generate_response` function to integrate the Gemini API for alternative service recommendations when content-based confidence is low or intent is unclear.

**Reasoning**:
I will define the system instruction for the Gemini model, configure the Gemini API with a placeholder for the API key, and create a Generative Model instance to prepare for integration into the `generate_response` function.
"""

import google.generativeai as genai
import os

# 1. Define a system instruction string for Gemini
system_instruction = (
    "You are a helpful and optimistic service recommendation chatbot. "
    "Your goal is to provide professional and encouraging service recommendations. "
    "When asked about a service, provide a positive and clear recommendation. "
    "If you are unsure, suggest exploring related options with a helpful tone."
)

# 2. Configure the Gemini API with your API key
# IMPORTANT: Ensure your Google API Key is set as an environment variable named 'GEMINI_API_KEY'.
# For example, in your environment or at the start of your Colab session:
# import os
# os.environ["GEMINI_API_KEY"] = "YOUR_ACTUAL_API_KEY"

genai.configure(
    api_key=os.environ.get("GEMINI_API_KEY")
)

# 3. Create a Gemini Generative Model instance
gemini_model = genai.GenerativeModel('gemini-pro')

print("Gemini API configured and model instance created. Please ensure GEMINI_API_KEY environment variable is set.")

"""**Reasoning**:
The previous steps successfully configured the Gemini API and created a `gemini_model` instance. Now, I will re-run the modified `generate_response` function to test the integration with the correctly initialized Gemini model and generate responses for the sample queries.


"""

import google.generativeai as genai # Ensure correct import as per previous step

def generate_response(query_text, recommended_service, confidence, predicted_intent_service):
    response = f"Great news! I found a highly recommended service for you: **{recommended_service}**.\n"
    gemini_alternative_response = None

    # Define thresholds for low confidence or unclear intent
    low_confidence_threshold = 0.1 # Using 0.1 as an example threshold
    is_low_confidence = confidence <= low_confidence_threshold
    is_unclear_intent = recommended_service != predicted_intent_service

    if is_low_confidence or is_unclear_intent:
        response += (f"While I'm suggesting **{recommended_service}**, my primary system indicates this with a confidence of {confidence:.2f}.\n")
        response += (f"And my intent recognition suggests **{predicted_intent_service}**.\n")
        response += ("To ensure we're on the right track, I've consulted with an advanced AI assistant to provide an alternative perspective.\n")

        try:
            # Call Gemini API for alternative recommendation
            # Ensure system_instruction and gemini_model are accessible in this scope
            gemini_response_obj = gemini_model.generate_content(
                system_instruction + "\n\nUser query: " + query_text
            )
            gemini_alternative_response = gemini_response_obj.text
            response += f"\nHere's what our advanced AI suggests based on your query: {gemini_alternative_response}\n"
            response += ("We're dedicated to finding the perfect match for your needs!\n")

        except Exception as e:
            response += f"However, I encountered an issue fetching an alternative recommendation from our advanced AI: {e}. I apologize for the inconvenience.\n"
            response += "Please bear with us as we improve our systems.\n"

    else:
        response += f"I'm quite confident about this recommendation (Confidence: {confidence:.2f}).\n"

    response += "We're here to ensure you get the best assistance possible. How else can I help you today?"
    return response

# Test the generate_response function with the output from recommend_service
# First sample query
sample_query_1 = "My air conditioning unit is not working, I need it fixed."
recommended_service_1, confidence_1, predicted_intent_1 = recommend_service(sample_query_1)
response_1 = generate_response(sample_query_1, recommended_service_1, confidence_1, predicted_intent_1)
print(f"--- Response for Query 1: '{sample_query_1}' ---")
print(response_1)

# Second sample query
sample_query_2 = "I have a leaky faucet in my kitchen."
recommended_service_2, confidence_2, predicted_intent_2 = recommend_service(sample_query_2)
response_2 = generate_response(sample_query_2, recommended_service_2, confidence_2, predicted_intent_2)
print(f"\n--- Response for Query 2: '{sample_query_2}' ---")
print(response_2)

"""### Action Required: Set Your Gemini API Key

It appears that the Gemini API key is not correctly configured, leading to authentication errors. To resolve this, please follow these steps:

1.  **Obtain Your API Key**: If you don't have one, get a Google Gemini API key from the [Google AI Studio](https://aistudio.google.com/app/apikey).

2.  **Set Environment Variable in Colab**: In a new code cell at the beginning of your notebook (or before the Gemini configuration step), set your API key as an environment variable named `GEMINI_API_KEY`. Replace `YOUR_ACTUAL_API_KEY` with the key you obtained.

    ```python
    import os
    os.environ["GEMINI_API_KEY"] = "YOUR_ACTUAL_API_KEY"
    ```

3.  **Re-run Configuration**: After setting the environment variable, please re-run the code cell (`d3d8f863`) that configures the Gemini API and creates the `gemini_model` instance.

4.  **Re-run `generate_response` Test**: Finally, re-run the code cell (`d4fbf658`) that defines and tests the `generate_response` function. This should now successfully integrate the Gemini API without authentication errors.

## Test Gemini Integration

### Subtask:
Verify that the `generate_response` function, now integrated with Gemini, correctly provides alternative recommendations when content-based confidence is low or intent is unclear, by running the previously defined sample queries after setting the `GEMINI_API_KEY`.

**Reasoning**:
The first instruction is to set the `GEMINI_API_KEY` as an environment variable. I will provide a code block for the user to set their API key.
"""

import os
from google.colab import userdata

# Set the GEMINI_API_KEY as an environment variable
# IMPORTANT: Replace "YOUR_ACTUAL_API_KEY" with your actual Google Gemini API key.
# You can obtain a key from Google AI Studio (https://aistudio.google.com/app/apikey).
os.environ["GEMINI_API_KEY"] = userdata.get('GEMINI_API_KEY')

print("GEMINI_API_KEY environment variable set. Please make sure you replaced 'YOUR_ACTUAL_API_KEY' with your valid key.")

"""**Reasoning**:
I will re-run the code cell with ID `d3d8f863` to configure the Gemini API and re-create the `gemini_model` instance, ensuring it uses the `GEMINI_API_KEY` that was just set.


"""

import google.generativeai as genai
import os

# 1. Define a system instruction string for Gemini
system_instruction = (
    "You are a helpful and optimistic service recommendation chatbot. "
    "Your goal is to provide professional and encouraging service recommendations. "
    "When asked about a service, provide a positive and clear recommendation. "
    "If you are unsure, suggest exploring related options with a helpful tone."
)

# 2. Configure the Gemini API with your API key
# IMPORTANT: Ensure your Google API Key is set as an environment variable named 'GEMINI_API_KEY'.
# For example, in your environment or at the start of your Colab session:
# import os
# os.environ["GEMINI_API_KEY"] = "YOUR_ACTUAL_API_KEY"

genai.configure(
    api_key=os.environ.get("GEMINI_API_KEY")
)

# 3. Create a Gemini Generative Model instance
gemini_model = genai.GenerativeModel('gemini-flash-latest')

print("Gemini API configured and model instance created. Please ensure GEMINI_API_KEY environment variable is set.")

"""**Reasoning**:
I will re-run the code cell with ID `d4fbf658` to define and test the `generate_response` function, which now integrates the Gemini API using the previously configured API key.


"""

import google.generativeai as genai # Ensure correct import as per previous step

def generate_response(query_text, recommended_service, confidence, predicted_intent_service):
    response = f"Great news! I found a highly recommended service for you: **{recommended_service}**.\n"
    gemini_alternative_response = None

    # Define thresholds for low confidence or unclear intent
    low_confidence_threshold = 0.1 # Using 0.1 as an example threshold
    is_low_confidence = confidence <= low_confidence_threshold
    is_unclear_intent = recommended_service != predicted_intent_service

    if is_low_confidence or is_unclear_intent:
        response += (f"While I'm suggesting **{recommended_service}**, my primary system indicates this with a confidence of {confidence:.2f}.\n")
        response += (f"And my intent recognition suggests **{predicted_intent_service}**.\n")
        response += ("To ensure we're on the right track, I've consulted with an advanced AI assistant to provide an alternative perspective.\n")

        try:
            # Call Gemini API for alternative recommendation
            # Ensure system_instruction and gemini_model are accessible in this scope
            gemini_response_obj = gemini_model.generate_content(
                system_instruction + "\n\nUser query: " + query_text
            )
            gemini_alternative_response = gemini_response_obj.text
            response += f"\nHere's what our advanced AI suggests based on your query: {gemini_alternative_response}\n"
            response += ("We're dedicated to finding the perfect match for your needs!\n")

        except Exception as e:
            response += f"However, I encountered an issue fetching an alternative recommendation from our advanced AI: {e}. I apologize for the inconvenience.\n"
            response += "Please bear with us as we improve our systems.\n"

    else:
        response += f"I'm quite confident about this recommendation (Confidence: {confidence:.2f}).\n"

    response += "We're here to ensure you get the best assistance possible. How else can I help you today?"
    return response

# Test the generate_response function with the output from recommend_service
# First sample query
sample_query_1 = "My air conditioning unit is not working, I need it fixed."
recommended_service_1, confidence_1, predicted_intent_1 = recommend_service(sample_query_1)
response_1 = generate_response(sample_query_1, recommended_service_1, confidence_1, predicted_intent_1)
print(f"--- Response for Query 1: '{sample_query_1}' ---")
print(response_1)

# Second sample query
sample_query_2 = "I have a leaky faucet in my kitchen."
recommended_service_2, confidence_2, predicted_intent_2 = recommend_service(sample_query_2)
response_2 = generate_response(sample_query_2, recommended_service_2, confidence_2, predicted_intent_2)
print(f"\n--- Response for Query 2: '{sample_query_2}' ---")
print(response_2)

"""## Final Task

### Subtask:
Provide a summary of the Gemini integration, highlighting its impact on the chatbot's ability to generate responses, especially for out-of-scope queries.

## Summary:

### Q&A
The Gemini integration significantly enhances the chatbot's ability to generate responses, especially for out-of-scope or unclear queries. By acting as an advanced AI assistant, Gemini provides alternative and often more relevant recommendations when the primary system's confidence is low or its intent recognition is unclear. This improves the chatbot's helpfulness and robustness, preventing it from giving potentially inaccurate or unhelpful single recommendations in ambiguous situations.

### Data Analysis Key Findings
*   The `google-genai` library was successfully installed and the correct module (`google.genai`) was identified for use, despite an initial deprecation warning for `google.generativeai`.
*   The chatbot's `generate_response` function was modified to integrate the Gemini API, specifically activating Gemini when the primary system's confidence in a recommendation is low (less than or equal to $0.1$) or the recommended service does not match the predicted intent.
*   Initially, the Gemini API integration faced issues due to an unconfigured API key and `AttributeError`s related to library imports. These were resolved by using `import google.generativeai as genai` (the compatible package name for the `genai.configure` and `genai.GenerativeModel` functions) and instructing the user to set the `GEMINI_API_KEY` environment variable.
*   After correctly setting the `GEMINI_API_KEY`, the Gemini integration successfully provided alternative recommendations for test queries:
    *   For the query "My air conditioning unit is not working, I need it fixed," where primary confidence was $0.23$ and intent was unclear, Gemini suggested an "HVAC repair service."
    *   For the query "I have a leaky faucet in my kitchen," where primary confidence was $0.00$ and intent was unclear, Gemini recommended a "licensed local plumber" or "professional handyman service."
*   Gemini's responses were relevant, detailed, and aimed at exploring related options, aligning with the system instruction to be helpful and optimistic.

### Insights or Next Steps
*   The Gemini integration successfully addresses the challenge of providing helpful responses for queries where the primary content-based recommendation system struggles with low confidence or unclear intent.
*   Further enhancements could include dynamically adjusting the confidence threshold for Gemini activation based on historical performance or user feedback, and refining Gemini's system instructions for even more tailored and specific alternative service recommendations.
"""